quarkus:
  datasource:
    db-kind: postgresql
    username: ${DB_USER:persons}
    password: ${DB_PASSWORD:persons}
    jdbc:
      url: jdbc:${quarkus.datasource.db-kind}://${DB_HOST:localhost:15432}/${DB_NAME:persons}